name: Bot de Ventas Diario

on:
  schedule:
    # Corre a las 11:00 UTC (6:00 AM Colombia)
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite correrlo manual

jobs:
  ejecutar-robot:
    runs-on: ubuntu-latest
    
    # --- CAMBIO CLAVE: DEFINICIÓN GLOBAL ---
    # Al ponerlos aquí, están disponibles para TODOS los pasos
    env:
      LOYVERSE_TOKEN: ${{ secrets.LOYVERSE_TOKEN }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install pandas requests gspread oauth2client pytz

      - name: Correr Script de Ventas
        # Ya no necesitamos definir 'env' aquí porque está arriba
        run: python daily_bot.py